### ISSUE TITLE
No permission to send message to these tmIDs

### ISSUE THREAD

**Issue by zjywill** [evercyan/hw_push#1]
接口一直返回
result {"msg":"No permission to send message to these tmIDs","requestId":"1545295163795280511","code":"80300002"}
有了解是什么原因导致的吗？
换了appid和secret了

**Comment by evercyan** [comment]
> 接口一直返回
> result {"msg":"No permission to send message to these tmIDs","requestId":"1545295163795280511","code":"80300002"}
> 有了解是什么原因导致的吗？
> 换了appid和secret了

直接去华为开发者文档里找对应错误的说明
